### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by doublehelixlf** [pachterlab/sircel#1]
After install, did a test run with example Drop-Seq reads files, using the following command:

python3 sircel/Sircel_master.py --threads 4 --dropseq --output_dir example_test --reads example/SRR1873277_1m_r2.fastq.gz --barcodes example/SRR1873277_1m_r1.fastq.gz --threads 4 --kallisto_idx /media/.../mouse_GRCm38cdna.idx

The program almost immediately stopped, with the following error message:

*******************************************************************
Initializing redis-db server
Traceback (most recent call last):
  File "/home/feng/anaconda3/lib/python3.5/site-packages/redis/connection.py", line 433, in connect
    sock = self._connect()
  File "/home/feng/anaconda3/lib/python3.5/site-packages/redis/connection.py", line 488, in _connect
    raise err
  File "/home/feng/anaconda3/lib/python3.5/site-packages/redis/connection.py", line 476, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused
*******************************************************************

Any suggestion to fix this?

Thanks,
Feng

**Comment by Simon-Coetzee** [comment]
Try running `redis-server` before running sircel

**Comment by doublehelixlf** [comment]
Thanks for the tip, Simon_Coetzee!
