### ISSUE TITLE
cannot start Sircel via ./sircel

### ISSUE THREAD

**Issue by doublehelixlf** [pachterlab/sircel#10]
After installing the most recent version of Sircel, it appears that there is no executable file named "sircel" in under the master folder. 

Therefore there is no way to run sircel via ./sircel

**Comment by axtambe** [comment]
If you install with the command: `python3 setup.py install --kallisto PATH_TO_KALLISTO `, the executable is by default placed in /usr/local/bin. 

To have the executable in the sircel/ directory, install with the following option
python3 setup.py install --kallisto PATH_TO_KALLISTO --install-scripts=./sircel/

Thanks for catching this
